name: Rfm69-rs-lib

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      working-directory: ./rfm69
      run: cargo build --verbose
    - name: Run tests
      working-directory: ./rfm69
      run: cargo test --verbose
