name: Rfm69-rs-lib

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      
    - uses: actions/checkout@v4
    - name: Build & Test
      run: cd rfm69-rs && cargo build --verbose && cargo test --verbose